#!/usr/bin/env bash
#
# Elektron Net -- one-shot install script (node + ppool + ppool-ui + faucet + Caddy)
#
# Usage:
#   1. Edit the CONFIG block below.
#   2. Copy this file onto the Hetzner server (Hetzner console / scp) as
#      install-elektron-stack.sh
#   3. chmod +x install-elektron-stack.sh
#   4. ./install-elektron-stack.sh
#
# Safe to re-run: existing clones/wallets are detected and skipped instead
# of being recreated or overwritten.

set -euo pipefail

# ============================================================================
# CONFIG -- edit everything in this block, then run the script
# ============================================================================

# --- General ---
STACK_DIR="/opt/elektron-net-stack"           # where everything gets installed
GITHUB_USER="kutlusoy"                        # github.com/<user>/elektron-net...
SERVER_IP="46.225.163.85"                     # only used for the DNS sanity check
# Fallback-Wert, falls die automatische Erkennung weiter unten (ip -6 addr)
# nichts findet. Das Hetzner-Panel zeigt im Networking-Tab nur das geroutete
# /64-Subnetz (z.B. 2a01:4f8:1c18:ea01::/64), NICHT die exakt konfigurierte
# Host-Adresse -- die wird gleich live auf diesem Server ausgelesen.
SERVER_IPV6="2a01:4f8:1c18:ea01::1"

# --- Domains (must already point to SERVER_IP in DNS, see README) ---
NODE_DOMAIN="node1.elektron-net.org"          # P2P seed only, no HTTP/Caddy block
POOL_DOMAIN="pplns.elektron-net.org"
FAUCET_DOMAIN="faucet.elektron-net.org"
CADDY_EMAIL=""                                # optional, for Let's Encrypt notices

# --- Node / RPC ---
RPC_USER="elektron_svc"                       # rpcauth username (password is auto-generated)

# --- Firewall ---
FIREWALL_AUTO_CONFIGURE=true                  # true = run ufw commands automatically

# --- Pool (elektron-net-ppool) ---
POOL_WALLET_NAME="pool"                       # wallet name on the node for pool payouts
POOL_IDENTIFIER="Elektron-PPLNS-Pool"
POOL_FEE_PERCENT="1.0"
PPLNS_WINDOW_MINUTES="90"
MIN_PAYOUT_THRESHOLD_SATS="100000"
PAYOUT_INTERVAL_MINUTES="60"
PAYOUT_CONFIRMATIONS_REQUIRED="1"
PAYOUT_DRY_RUN="true"                         # keep true until you've verified payouts!
STRATUM_PORT="3333"
API_PORT="3334"
# leave empty to auto-generate a random 32-byte hex secret:
JWT_SECRET=""

# --- Faucet (elektron-net-faucet) ---
FAUCET_WALLET_NAME="faucet"                   # wallet name on the node for faucet payouts
# leave empty to auto-generate a strong passphrase (printed at the end -- save it!):
FAUCET_WALLET_PASSPHRASE=""
FAUCET_DB_NAME="elek_faucet"
FAUCET_DB_USER="elek_faucet"
# leave empty to auto-generate:
FAUCET_DB_PASS=""
FAUCET_DB_ROOT_PASS=""
FAUCET_ADMIN_USER="admin"
# leave empty to auto-generate (min 10 chars required by the faucet):
FAUCET_ADMIN_PASS=""
FAUCET_HCAPTCHA_SITE=""                       # from hcaptcha.com -- strongly recommended
FAUCET_HCAPTCHA_SECRET=""
FAUCET_TITLE="Elektron Net Faucet"
FAUCET_MESSAGE="Claim some free ELEK!"
FAUCET_AMOUNT_ELEK="0.001"
FAUCET_DAILY_BUDGET="1"
FAUCET_HOURLY_BUDGET="0.1"
FAUCET_PER_ADDR_COOLDOWN_H="24"
FAUCET_PER_IP_COOLDOWN_H="1"
FAUCET_DEFAULT_LANG="de"

# ============================================================================
# END CONFIG -- nothing below this line needs editing for a normal install
# ============================================================================

log()  { printf '\n\033[1;32m==>\033[0m %s\n' "$1"; }
warn() { printf '\n\033[1;33m!!\033[0m %s\n' "$1"; }
die()  { printf '\n\033[1;31mERROR:\033[0m %s\n' "$1"; exit 1; }

rand_hex()    { openssl rand -hex "$1"; }
rand_base64() { openssl rand -base64 "$1" | tr -d '=+/\n' | cut -c1-"$1"; }

# Auto-generate any secret left blank in the CONFIG block above.
# Track which ones were actually auto-generated (vs. supplied by you) so the
# final summary can say so explicitly instead of just silently using them.
GENERATED_SECRETS=""
[ -z "$JWT_SECRET" ]              && { JWT_SECRET="$(rand_hex 32)"; GENERATED_SECRETS="${GENERATED_SECRETS}JWT_SECRET "; }
[ -z "$FAUCET_WALLET_PASSPHRASE" ] && { FAUCET_WALLET_PASSPHRASE="$(rand_base64 32)"; GENERATED_SECRETS="${GENERATED_SECRETS}FAUCET_WALLET_PASSPHRASE "; }
[ -z "$FAUCET_DB_PASS" ]          && { FAUCET_DB_PASS="$(rand_base64 24)"; GENERATED_SECRETS="${GENERATED_SECRETS}FAUCET_DB_PASS "; }
[ -z "$FAUCET_DB_ROOT_PASS" ]     && { FAUCET_DB_ROOT_PASS="$(rand_base64 24)"; GENERATED_SECRETS="${GENERATED_SECRETS}FAUCET_DB_ROOT_PASS "; }
[ -z "$FAUCET_ADMIN_PASS" ]       && { FAUCET_ADMIN_PASS="$(rand_base64 16)"; GENERATED_SECRETS="${GENERATED_SECRETS}FAUCET_ADMIN_PASS "; }
# RPC_USER/RPC_PASSWORD are always auto-generated by rpcauth.py further down
# (there's no CONFIG variable for the RPC password -- rpcauth.py makes its
# own if you don't pass one, see step 3 below), so it's always "generated".

command -v docker >/dev/null 2>&1 || die "Docker ist nicht installiert."
docker compose version >/dev/null 2>&1 || die "Docker Compose Plugin fehlt."
command -v git >/dev/null 2>&1    || die "git ist nicht installiert."
command -v python3 >/dev/null 2>&1 || die "python3 ist nicht installiert (wird für rpcauth.py gebraucht)."
command -v openssl >/dev/null 2>&1 || die "openssl ist nicht installiert."

# --- Tatsächlich konfigurierte IPv6-Adresse auf diesem Server auslesen ---
# Das Hetzner-Panel zeigt nur das geroutete /64, nicht die konkrete Adresse,
# die der Server sich selbst gegeben hat -- also lieber direkt nachsehen,
# statt der Fallback-Annahme (::1) blind zu vertrauen.
DETECTED_IPV6="$(ip -6 addr show scope global 2>/dev/null | awk '/inet6/{print $2}' | cut -d/ -f1 | grep -v '^fe80' | head -n1 || true)"
if [ -n "$DETECTED_IPV6" ] && [ "$DETECTED_IPV6" != "$SERVER_IPV6" ]; then
  warn "Erkannte IPv6-Adresse auf diesem Server ($DETECTED_IPV6) weicht vom CONFIG-Wert ($SERVER_IPV6) ab -- verwende die erkannte Adresse."
  SERVER_IPV6="$DETECTED_IPV6"
elif [ -z "$DETECTED_IPV6" ]; then
  warn "Konnte keine globale IPv6-Adresse auf diesem Server finden -- IPv6 evtl. noch nicht konfiguriert. Verwende weiterhin den CONFIG-Wert ($SERVER_IPV6), bitte prüfen."
fi

# --- Soft DNS sanity check (does not abort on mismatch, just warns) ---
for d in "$NODE_DOMAIN" "$POOL_DOMAIN" "$FAUCET_DOMAIN"; do
  resolved="$(getent hosts "$d" 2>/dev/null | awk '{print $1}' | head -n1 || true)"
  if [ -z "$resolved" ]; then
    warn "$d löst (noch) nicht auf. Caddy wird für dieses Encpoint kein TLS bekommen, bis DNS propagiert ist."
  elif [ "$resolved" != "$SERVER_IP" ]; then
    warn "$d löst auf $resolved auf, nicht auf $SERVER_IP. Bitte DNS-Eintrag prüfen."
  fi

  resolved6="$(getent ahostsv6 "$d" 2>/dev/null | awk '{print $1}' | head -n1 || true)"
  if [ -z "$resolved6" ]; then
    warn "$d hat (noch) keinen AAAA-Eintrag -- IPv6-Erreichbarkeit fehlt, IPv4 funktioniert trotzdem."
  elif [ "$resolved6" != "$SERVER_IPV6" ]; then
    warn "$d (AAAA) löst auf $resolved6 auf, nicht auf $SERVER_IPV6. Bitte DNS-Eintrag prüfen."
  fi
done

# ============================================================================
# 1. Repos klonen
# ============================================================================
mkdir -p "$STACK_DIR"
cd "$STACK_DIR"

clone_or_skip() {
  local repo="$1"
  if [ -d "$repo/.git" ]; then
    log "Repo $repo existiert schon (vollständiger git-Klon), überspringe."
    return
  fi

  if [ -d "$repo" ] && [ "$(ls -A "$repo" 2>/dev/null)" ]; then
    # Verzeichnis existiert bereits und ist nicht leer -- typischerweise weil
    # es aus DIESEM Deploy-Repo (elektron-net-stack) kommt und schon unsere
    # Zusatzdateien enthält (Dockerfile, bitcoin.conf, .env-Template, ...).
    # `git clone` würde hier mit "destination path already exists and is
    # not an empty directory" abbrechen -- also stattdessen in ein
    # Temp-Verzeichnis klonen und nur das reinkopieren, was noch nicht da
    # ist (unsere bereits vorhandenen Dateien bleiben unangetastet).
    log "Verzeichnis $repo existiert schon und ist nicht leer -- klone Upstream in ein Temp-Verzeichnis und merge non-destruktiv rein."
    local tmp
    tmp="$(mktemp -d)"
    git clone "https://github.com/${GITHUB_USER}/${repo}.git" "$tmp"
    rm -rf "$tmp/.git"
    cp -rn "$tmp"/. "$repo"/
    rm -rf "$tmp"
  else
    log "Klone $repo ..."
    git clone "https://github.com/${GITHUB_USER}/${repo}.git" "$repo"
  fi
}

clone_or_skip "elektron-net"
clone_or_skip "elektron-net-ppool"
clone_or_skip "elektron-net-ppool-ui"
clone_or_skip "elektron-net-faucet"

mkdir -p caddy data/elektron-net data/ppool-DB data/faucet-db data/faucet-config

# ============================================================================
# 2. elektron-net: Dockerfile + Entrypoint (existieren im Repo noch nicht)
# ============================================================================
log "Schreibe elektron-net/Dockerfile ..."
cat > elektron-net/Dockerfile <<'DOCKERFILE_EOF'
############################
# Build stage              #
############################
FROM debian:bookworm-slim AS build

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential cmake pkgconf python3 \
        libevent-dev libboost-dev libsqlite3-dev libzmq3-dev \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build
COPY . .

RUN cmake -B build \
        -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_GUI=OFF \
        -DWITH_ZMQ=ON \
    && cmake --build build -j"$(nproc)" \
    && cmake --install build

############################
# Runtime stage            #
############################
FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
        libevent-2.1-7 libevent-pthreads-2.1-7 \
        libsqlite3-0 libzmq5 \
        ca-certificates gosu \
    && rm -rf /var/lib/apt/lists/* \
    && groupadd -r elektron && useradd -r -g elektron -d /data -s /usr/sbin/nologin elektron \
    && mkdir -p /data && chown elektron:elektron /data

COPY --from=build /usr/local/bin/elektron* /usr/local/bin/

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

VOLUME ["/data"]
EXPOSE 8333 8332

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["elektrond", "-conf=/data/bitcoin.conf", "-datadir=/data", "-printtoconsole"]
DOCKERFILE_EOF

log "Schreibe elektron-net/docker-entrypoint.sh ..."
cat > elektron-net/docker-entrypoint.sh <<'ENTRYPOINT_EOF'
#!/bin/sh
set -e
chown -R elektron:elektron /data
exec gosu elektron "$@"
ENTRYPOINT_EOF
chmod +x elektron-net/docker-entrypoint.sh

# ============================================================================
# 3. rpcauth generieren
# ============================================================================
log "Generiere RPC-Zugangsdaten (rpcauth.py) ..."
RPCAUTH_JSON="$(python3 elektron-net/share/rpcauth/rpcauth.py "$RPC_USER" -j)"
RPC_AUTH_LINE="$(python3 -c "import json,sys; d=json.loads(sys.argv[1]); print(d['rpcauth'])" "$RPCAUTH_JSON")"
RPC_PASSWORD="$(python3 -c "import json,sys; d=json.loads(sys.argv[1]); print(d['password'])" "$RPCAUTH_JSON")"

# ============================================================================
# 4. elektron-net/bitcoin.conf
# ============================================================================
log "Schreibe elektron-net/bitcoin.conf ..."
cat > elektron-net/bitcoin.conf <<CONF_EOF
server=1
listen=1
bind=0.0.0.0:8333
maxconnections=125

rpcbind=0.0.0.0
rpcallowip=172.16.0.0/12
rpcauth=${RPC_AUTH_LINE}

zmqpubrawblock=tcp://0.0.0.0:28332
zmqpubrawtx=tcp://0.0.0.0:28333

disablewallet=0
CONF_EOF

# ============================================================================
# 5. docker-compose.yml
# ============================================================================
log "Schreibe docker-compose.yml ..."
cat > docker-compose.yml <<'COMPOSE_EOF'
services:

  elektron-net:
    container_name: elektron-net
    build:
      context: ./elektron-net
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "8333:8333"
      - "[::]:8333:8333"
    volumes:
      - "./elektron-net/bitcoin.conf:/data/bitcoin.conf:ro"
      - "./data/elektron-net:/data"

  elektron-ppool:
    container_name: elektron-ppool
    build:
      context: ./elektron-net-ppool
    restart: unless-stopped
    depends_on:
      - elektron-net
    networks:
      - backend
    ports:
      - "3333:3333"
      - "[::]:3333:3333"
    volumes:
      - "./elektron-net-ppool/.env:/elektron-pool/.env:ro"
      - "./data/ppool-DB:/elektron-pool/DB"

  elektron-ppool-ui:
    container_name: elektron-ppool-ui
    build:
      context: ./elektron-net-ppool-ui
    restart: unless-stopped
    depends_on:
      - elektron-ppool
    networks:
      - backend
      - web
    environment:
      - API_UPSTREAM=elektron-ppool:3334

  elektron-faucet-db:
    container_name: elektron-faucet-db
    image: mariadb:11.4
    restart: unless-stopped
    env_file: ./elektron-net-faucet/.env
    environment:
      MYSQL_DATABASE: ${FAUCET_DB_NAME}
      MYSQL_USER: ${FAUCET_DB_USER}
      MYSQL_PASSWORD: ${FAUCET_DB_PASS}
      MYSQL_ROOT_PASSWORD: ${FAUCET_DB_ROOT_PASS}
    networks:
      - backend
    volumes:
      - "./data/faucet-db:/var/lib/mysql"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 5s
      retries: 20

  elektron-faucet-app:
    container_name: elektron-faucet-app
    build:
      context: ./elektron-net-faucet
    restart: unless-stopped
    depends_on:
      elektron-faucet-db:
        condition: service_healthy
      elektron-net:
        condition: service_started
    env_file: ./elektron-net-faucet/.env
    environment:
      FAUCET_CONFIG: /config/config.php
    networks:
      - backend
      - web
    volumes:
      - "./data/faucet-config:/config"

  caddy:
    container_name: elektron-caddy
    image: caddy:2-alpine
    restart: unless-stopped
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
      - "[::]:80:80"
      - "[::]:443:443"
    volumes:
      - "./caddy/Caddyfile:/etc/caddy/Caddyfile:ro"
      - "caddy_data:/data"
      - "caddy_config:/config"

networks:
  backend:
  web:

volumes:
  caddy_data:
  caddy_config:
COMPOSE_EOF

# ============================================================================
# 6. Caddyfile
# ============================================================================
log "Schreibe caddy/Caddyfile ..."
{
  if [ -n "$CADDY_EMAIL" ]; then
    echo "{"
    echo "	email ${CADDY_EMAIL}"
    echo "}"
    echo
  fi
  echo "# ${NODE_DOMAIN} bekommt bewusst keinen Block -- reiner P2P-Seed (Port 8333)."
  echo
  echo "${POOL_DOMAIN} {"
  echo "	reverse_proxy elektron-ppool-ui:80"
  echo "}"
  echo
  echo "${FAUCET_DOMAIN} {"
  echo "	reverse_proxy elektron-faucet-app:80"
  echo "}"
} > caddy/Caddyfile

# ============================================================================
# 7. elektron-net-ppool/.env
# ============================================================================
log "Schreibe elektron-net-ppool/.env ..."
cat > elektron-net-ppool/.env <<ENV_EOF
ELEKTRON_RPC_URL=http://elektron-net
ELEKTRON_RPC_USER=${RPC_USER}
ELEKTRON_RPC_PASSWORD=${RPC_PASSWORD}
ELEKTRON_RPC_PORT=8332
ELEKTRON_RPC_TIMEOUT=10000
ELEKTRON_ZMQ_HOST=tcp://elektron-net:28332

API_PORT=${API_PORT}
STRATUM_PORT=${STRATUM_PORT}
STRATUM_MAX_CONNECTIONS_PER_LISTENER=10000
JOB_REFRESH_INTERVAL_MS=30000
DIFFICULTY_CHECK_INTERVAL_MS=60000

NETWORK=mainnet
API_SECURE=false
POOL_IDENTIFIER="${POOL_IDENTIFIER}"

HOBBY_MINER_USER_AGENTS=NerdMiner,NerdminerV2,nerdminer,NerdAxe,NerdQAxe
HOBBY_MINER_DIFFICULTY=0.001
DIAGNOSTIC_SHARE_LOGGING_MODES=

# wird nach der Wallet-Erstellung automatisch von diesem Skript eingetragen:
POOL_WALLET_ADDRESS=

PPLNS_WINDOW_MINUTES=${PPLNS_WINDOW_MINUTES}
POOL_FEE_PERCENT=${POOL_FEE_PERCENT}
MIN_PAYOUT_THRESHOLD_SATS=${MIN_PAYOUT_THRESHOLD_SATS}
PAYOUT_INTERVAL_MINUTES=${PAYOUT_INTERVAL_MINUTES}
PAYOUT_CONFIRMATIONS_REQUIRED=${PAYOUT_CONFIRMATIONS_REQUIRED}
PAYOUT_DRY_RUN=${PAYOUT_DRY_RUN}

WALLET_RPC_WALLET_NAME=${POOL_WALLET_NAME}

JWT_SECRET=${JWT_SECRET}
ENV_EOF

# ============================================================================
# 8. elektron-net-faucet/.env
# ============================================================================
log "Schreibe elektron-net-faucet/.env ..."
cat > elektron-net-faucet/.env <<ENV_EOF
FAUCET_PORT=8080

FAUCET_DB_HOST=elektron-faucet-db
FAUCET_DB_PORT=3306
FAUCET_DB_NAME=${FAUCET_DB_NAME}
FAUCET_DB_USER=${FAUCET_DB_USER}
FAUCET_DB_PASS=${FAUCET_DB_PASS}
FAUCET_DB_ROOT_PASS=${FAUCET_DB_ROOT_PASS}

FAUCET_ADMIN_USER=${FAUCET_ADMIN_USER}
FAUCET_ADMIN_PASS=${FAUCET_ADMIN_PASS}

FAUCET_RPC_HOST=http://elektron-net
FAUCET_RPC_PORT=8332
FAUCET_RPC_USER=${RPC_USER}
FAUCET_RPC_PASS=${RPC_PASSWORD}
FAUCET_WALLET_NAME=${FAUCET_WALLET_NAME}
FAUCET_WALLET_PASS=${FAUCET_WALLET_PASSPHRASE}
FAUCET_RPC_TLS_VERIFY=1
FAUCET_RPC_TLS_VERIFY_HOST=0

FAUCET_HCAPTCHA_SITE=${FAUCET_HCAPTCHA_SITE}
FAUCET_HCAPTCHA_SECRET=${FAUCET_HCAPTCHA_SECRET}

FAUCET_TITLE=${FAUCET_TITLE}
FAUCET_MESSAGE=${FAUCET_MESSAGE}
FAUCET_AMOUNT_ELEK=${FAUCET_AMOUNT_ELEK}
FAUCET_DAILY_BUDGET=${FAUCET_DAILY_BUDGET}
FAUCET_HOURLY_BUDGET=${FAUCET_HOURLY_BUDGET}
FAUCET_PER_ADDR_COOLDOWN_H=${FAUCET_PER_ADDR_COOLDOWN_H}
FAUCET_PER_IP_COOLDOWN_H=${FAUCET_PER_IP_COOLDOWN_H}
# wird nach der Wallet-Erstellung automatisch von diesem Skript eingetragen:
FAUCET_SENDER_ADDR=
FAUCET_EXPLORER_URL=
FAUCET_DEFAULT_LANG=${FAUCET_DEFAULT_LANG}
ENV_EOF

# Docker Compose braucht eine .env im Projekt-Root, um ${FAUCET_DB_*} in
# docker-compose.yml aufzulösen -- Symlink hält beide Dateien synchron.
ln -sf elektron-net-faucet/.env .env

# ============================================================================
# 9. Node zuerst hochfahren
# ============================================================================
log "Baue und starte elektron-net ..."
docker compose up -d --build elektron-net

wait_for_rpc() {
  local retries=60 i=0
  until docker compose exec -T elektron-net elektron-cli getblockchaininfo >/dev/null 2>&1; do
    i=$((i + 1))
    [ "$i" -ge "$retries" ] && die "Timeout: elektron-net RPC antwortet nach 5 Minuten nicht."
    sleep 5
  done
}

log "Warte auf RPC-Bereitschaft von elektron-net ..."
wait_for_rpc

# ============================================================================
# 10. Wallets anlegen -- PFLICHT für Pool und Faucet
# ============================================================================
wallet_loaded() {
  docker compose exec -T elektron-net elektron-cli listwallets | grep -q "\"$1\""
}

create_wallet_if_missing() {
  local wname="$1"
  if wallet_loaded "$wname"; then
    log "Wallet '$wname' ist bereits vorhanden/geladen, überspringe Erstellung."
  else
    log "Erstelle Wallet '$wname' ..."
    docker compose exec -T elektron-net elektron-cli createwallet "$wname" >/dev/null \
      || docker compose exec -T elektron-net elektron-cli loadwallet "$wname" >/dev/null
  fi
}

log "Lege Pool-Wallet an ..."
create_wallet_if_missing "$POOL_WALLET_NAME"
POOL_ADDR="$(docker compose exec -T elektron-net elektron-cli -rpcwallet="$POOL_WALLET_NAME" getnewaddress "" bech32 | tr -d '\r\n')"
sed -i "s#^POOL_WALLET_ADDRESS=.*#POOL_WALLET_ADDRESS=${POOL_ADDR}#" elektron-net-ppool/.env
log "Pool-Wallet-Adresse: ${POOL_ADDR}"

log "Lege Faucet-Wallet an ..."
create_wallet_if_missing "$FAUCET_WALLET_NAME"

# Verschlüsseln, falls noch nicht verschlüsselt (encryptwallet stoppt den
# Node-Prozess -- das ist normales Bitcoin-Core-Verhalten, der Container
# kommt dank restart:unless-stopped von selbst wieder hoch).
WALLET_INFO="$(docker compose exec -T elektron-net elektron-cli -rpcwallet="$FAUCET_WALLET_NAME" getwalletinfo)"
if echo "$WALLET_INFO" | grep -q '"unlocked_until"'; then
  log "Faucet-Wallet ist bereits verschlüsselt, überspringe encryptwallet."
else
  log "Verschlüssele Faucet-Wallet (Node startet dabei kurz neu) ..."
  docker compose exec -T elektron-net elektron-cli -rpcwallet="$FAUCET_WALLET_NAME" encryptwallet "$FAUCET_WALLET_PASSPHRASE" || true
  sleep 8
  wait_for_rpc
  wallet_loaded "$FAUCET_WALLET_NAME" || docker compose exec -T elektron-net elektron-cli loadwallet "$FAUCET_WALLET_NAME" >/dev/null
fi

FAUCET_ADDR="$(docker compose exec -T elektron-net elektron-cli -rpcwallet="$FAUCET_WALLET_NAME" getnewaddress "" bech32 | tr -d '\r\n')"
sed -i "s#^FAUCET_SENDER_ADDR=.*#FAUCET_SENDER_ADDR=${FAUCET_ADDR}#" elektron-net-faucet/.env
log "Faucet-Wallet-Adresse: ${FAUCET_ADDR}"

# ============================================================================
# 11. Rest des Stacks hochfahren
# ============================================================================
log "Baue und starte den restlichen Stack (ppool, ppool-ui, faucet, caddy) ..."
docker compose up -d --build

# ============================================================================
# 12. Firewall
# ============================================================================
if command -v ufw >/dev/null 2>&1; then
  if [ "$FIREWALL_AUTO_CONFIGURE" = "true" ]; then
    log "Konfiguriere ufw (IPv4 + IPv6) ..."
    # Ubuntu default: /etc/default/ufw hat IPV6=yes -- ufw legt dann für
    # jede Regel automatisch auch die passende ip6tables-Regel an.
    if grep -q '^IPV6=no' /etc/default/ufw 2>/dev/null; then
      warn "IPv6 war in /etc/default/ufw deaktiviert -- aktiviere es."
      sed -i 's/^IPV6=no/IPV6=yes/' /etc/default/ufw
    fi
    ufw allow 8333/tcp comment 'Elektron P2P seed' || true
    ufw allow 3333/tcp comment 'Elektron PPLNS Stratum' || true
    ufw allow 80/tcp  || true
    ufw allow 443/tcp || true
    ufw reload || true
  else
    warn "FIREWALL_AUTO_CONFIGURE=false -- bitte manuell öffnen: ufw allow 8333/tcp 3333/tcp 80/tcp 443/tcp"
  fi
else
  warn "ufw nicht gefunden -- Ports 8333, 3333, 80, 443 manuell im Hetzner Cloud Firewall öffnen."
fi
warn "Zusätzlich im Hetzner Cloud-Firewall-Panel (Tab 'Firewalls') dieselben 4 Ports öffnen -- dort für IPv4 UND IPv6 getrennt aktivieren, ufw allein reicht bei Cloud-Firewalls nicht."

# ============================================================================
# 13. Zusammenfassung
# ============================================================================
cat <<SUMMARY

============================================================================
 FERTIG
============================================================================

 Node (P2P-Seed):     ${NODE_DOMAIN}:8333
 Server IPv4:          ${SERVER_IP}
 Server IPv6 (erkannt/verwendet): ${SERVER_IPV6}
 Pool Dashboard:       https://${POOL_DOMAIN}
 Faucet:               https://${FAUCET_DOMAIN}
 Faucet Admin:          https://${FAUCET_DOMAIN}/admin.php
   User:     ${FAUCET_ADMIN_USER}
   Passwort: ${FAUCET_ADMIN_PASS}

 Pool-Wallet-Adresse:   ${POOL_ADDR}
 Faucet-Wallet-Adresse: ${FAUCET_ADDR}

 ----------------------------------------------------------------------------
 ALLE ZUGANGSDATEN AUF EINEN BLICK (jetzt kopieren, wird nicht nochmal so
 vollständig angezeigt -- danach musst du sie aus den .env-Dateien lesen,
 siehe Befehle ganz unten):

   RPC-Benutzer (Node):          ${RPC_USER}
   RPC-Passwort (Node):          ${RPC_PASSWORD}
   Pool JWT_SECRET:              ${JWT_SECRET}
   Faucet-DB-Passwort:           ${FAUCET_DB_PASS}
   Faucet-DB-Root-Passwort:      ${FAUCET_DB_ROOT_PASS}
   Faucet-Admin-Passwort:        ${FAUCET_ADMIN_PASS}
   Faucet-Wallet-Passphrase:     ${FAUCET_WALLET_PASSPHRASE}

 Automatisch generiert wurden (weil im CONFIG-Block leer gelassen):
   ${GENERATED_SECRETS:-"(nichts -- du hattest bereits alles selbst eingetragen)"}
 Alles andere oben hast du selbst im CONFIG-Block vorgegeben.
 ----------------------------------------------------------------------------

 NÄCHSTE SCHRITTE:
 1. Beide Adressen oben von deinem Prepaid-Bestand aus mit ELEK befüllen
    (Hot Wallet klein halten).
 2. https://${FAUCET_DOMAIN}/admin.php -> Settings -> "Test RPC connection"
    und "Test wallet unlock" grün bekommen.
 3. public/install.php im Faucet löschen:
    docker compose -f ${STACK_DIR}/docker-compose.yml exec elektron-faucet-app rm -f public/install.php
 4. elektron-net-ppool/.env: PAYOUT_DRY_RUN=true lassen, bis eine simulierte
    Auszahlung im Log geprüft wurde, dann auf false stellen und
    'docker compose up -d --force-recreate elektron-ppool' ausführen.
 5. hCaptcha-Keys nachtragen, falls beim Ausführen leer gelassen.
 6. Falls noch nicht geschehen: AAAA-Records bei world4you anlegen
    (${NODE_DOMAIN}, ${POOL_DOMAIN}, ${FAUCET_DOMAIN} -> ${SERVER_IPV6}).
    P2P (8333), Stratum (3333) und Caddy (80/443) sind bereits Dual-Stack
    published -- sobald AAAA existiert, funktioniert alles auch über IPv6.
 7. Optional, aber für einen öffentlichen Seed-Node empfehlenswert: Reverse
    DNS (PTR) für ${SERVER_IPV6} im Hetzner-Panel setzen (Networking -> bei
    der IPv6-Zeile die "..." -> Reverse DNS, zeigte bei dir "0 Einträge"),
    z.B. auf ${NODE_DOMAIN} -- viele Peers werten das bei der Node-Reputation
    positiv.

 Hinweis zur privaten Netzwerk-IP (10.0.0.2, Hetzner vSwitch):
 Wird von diesem Stack aktuell nicht gebraucht -- alle Container sprechen
 intern über Docker-eigene Netzwerke. Nützlich erst, falls du später z.B.
 die Wallet auf einen zweiten, isolierten Hetzner-Server auslagerst (siehe
 ppool-README §9, "network-isolated wallet server").

 Alle Secrets liegen dauerhaft in (jederzeit später wieder auslesbar):
   ${STACK_DIR}/elektron-net-ppool/.env
   ${STACK_DIR}/elektron-net-faucet/.env
 (chmod 600, nicht committen.)

 So bekommst du die Werte SPÄTER wieder, ohne das Skript erneut laufen zu
 lassen (die obige Anzeige gibt's nur bei diesem einen Lauf):

   cat ${STACK_DIR}/elektron-net-ppool/.env
   cat ${STACK_DIR}/elektron-net-faucet/.env

 Oder gezielt ein einzelnes Feld, z.B. das Faucet-Admin-Passwort:

   grep FAUCET_ADMIN_PASS ${STACK_DIR}/elektron-net-faucet/.env

 Die node.conf mit dem rpcauth-Eintrag (Hash, nicht das Klartext-Passwort):
   cat ${STACK_DIR}/elektron-net/bitcoin.conf

 WICHTIG: encryptwallet ist ein Einwegvorgang -- die
 Faucet-Wallet-Passphrase oben steht NUR in
 ${STACK_DIR}/elektron-net-faucet/.env (Feld FAUCET_WALLET_PASS). Es gibt
 keine andere Kopie, auch nicht auf der Blockchain. Verlierst du diese
 Datei, ist das Faucet-Wallet-Guthaben nicht mehr ausgebbar.
============================================================================
SUMMARY
